# Database
spring.datasource.url: jdbc:mysql://localhost:3306/pika_auth?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&useUnicode=yes
spring.datasource.username: root
spring.datasource.password: root
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.jpa.show-sql: true
spring.datasource.testWhileIdle: true
spring.datasource.validationQuery: SELECT 1
spring.datasource.initialization-mode: always
spring.jpa.database: MYSQL
spring.datasource.platform: mysql
spring.datasource.tomcat.initSQL: SET NAMES 'utf8mb4'
spring.jpa.hibernate.ddl-auto: validate

# Eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:5551/eureka/
server:
  port: 5554
spring:
  application: 
    name: pika-v1-auth
