server:
  port: 5554
## App Version
app:
  version: @project.version@
spring:
  application: 
    name: pika-v1-auth
  profiles:
    active: dev
  zipkin:
    base-url: http://127.0.0.1:9411/
  datasource:
    url: jdbc:mysql://localhost:3306/pika_auth?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&useUnicode=yes
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    platform: mysql
    tomcat:
      initSQL: SET NAMES 'utf8mb4'
  jpa:
    show-sql: true
    hibernate.ddl-auto: validate
    database: MYSQL
  flyway:
    baselineOnMigrate: true
    locations: "classpath:db/migration"

# Database
# spring.datasource.url: jdbc:mysql://localhost:3306/pika_auth?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&useUnicode=yes
# spring.datasource.username: root
# spring.datasource.password: root
# spring.datasource.driver-class-name: com.mysql.jdbc.Driver
# spring.jpa.show-sql: true
# spring.datasource.testWhileIdle: true
# spring.datasource.validationQuery: SELECT 1
# spring.jpa.database: MYSQL
# spring.datasource.platform: mysql
# spring.datasource.tomcat.initSQL: SET NAMES 'utf8mb4'
# spring.jpa.hibernate.ddl-auto: validate
# flyway
# flyway:
#   baselineOnMigrate: true
# Eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:5551/eureka/


