# Database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pika_auth?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&useUnicode=yes
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      show-sql: true
      testWhileIdle: true
      validationQuery: SELECT 1
      platform: mysql
      initialization-mode: always
      tomcat.initSQL: SET NAMES 'utf8mb4'
  jpa:
    database: MYSQL
    hibernate.ddl-auto: validate
# Eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:5551/eureka/
server:
  port: 5554
spring:
  application: 
    name: pika-v1-auth
