version: '3'
services:
  mongo:
        image: mongo:latest
        container_name: mongo
        ports:
            - 27017:27017
        volumes:
            - metadata_data:/data/db
volumes:
  metadata_data: {}

    