server:
  port: 5555
app:
  version: @project.version@
spring:
  application: 
    name: pika-v1-customer
  profiles:
    active: dev
  zipkin:
    base-url: http://127.0.0.1:9411/
  datasource:
    url: jdbc:mysql://localhost:3306/pika_customer?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&useUnicode=yes
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    platform: mysql
    tomcat:
      initSQL: SET NAMES 'utf8mb4'
  jpa:
    show-sql: true
    hibernate.ddl-auto: validate
    database: MYSQL

# Eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:5551/eureka/
