version: '3'
services:
  mysql:
        image: mysql:8.0
        container_name: mysql
        ports:
            - 3306:3306
        volumes:
            - metadata_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: pika
            MYSQL_PASSWORD: pika1234
volumes:
  metadata_data: {}

    